
# all variables from: https://fishshell.com/docs/current/interactive.html?highlight=fish_color_normal#variables-color

set fish_color_normal brwhite
set fish_color_command brgreen
set fish_color_keyword brmagenta
set fish_color_quote magenta
set fish_color_redirection brmagenta
set fish_color_end white
set fish_color_error brred
set fish_color_param yellow
set fish_color_comment brblue
set fish_color_selection -b white
set fish_color_selection black
set fish_color_operator brcyan
set fish_color_escape blue
set fish_color_autosuggestion white
set fish_color_cancel red
set fish_color_autosuggestion cyan
set fish_color_search_match yellow

set fish_pager_color_progress white
set fish_pager_color_background black
set fish_pager_color_prefix white
set fish_pager_color_completion white
set fish_pager_color_description white
set fish_pager_color_selected_background yellow --background=black
set fish_pager_color_selected_prefix yellow
set fish_pager_color_selected_completion green
set fish_pager_color_selected_description white
set fish_pager_color_secondary_background magenta
set fish_pager_color_secondary_prefix white
set fish_pager_color_secondary_completion white
set fish_pager_color_secondary_description white
